### PR TITLE
Misc updates

### PR DESCRIPTION
**Pull request by ivandorte**
Changes:
- Switched from holoviews to hvplot.xarray;
- Added rasterization for both RGB and spectral index maps;
- Added OSM basemap;
- Added a button to show the KDE plot of the selected spectral index (FloatPanel);
- Added a button to show the spectral index metadata (FloatPanel);
- Added an option to mask the clouds for both RGB and spectral index maps;
- Simplified the xarray processing pipeline;

### CODE REVIEW

**Comment by lalligagger** [comment]
I'm going to do a pretty quick merge on this - lmk if there is anything in particular you'd like me to review or test.

**Comment by ivandorte** [comment]
> I'm going to do a pretty quick merge on this - lmk if there is anything in particular you'd like me to review or test.

Yes, i forgot to test the datetime selector.

**Comment by lalligagger** [comment]
No issues switching dates. I'm not sure how to call the new views though. Looking into it.

**Comment by lalligagger** [comment]
Ok, merged. All of the previous functionality through chatbox is working fine. I see that you have your updates in the (working again) `app.py`... this is good, I will use it as a template for the full datacube view in chatbox demo.

**Pull request merged**
